name = "Phunky"
uuid = "3b2b43e2-0ac9-48cd-b393-3be551a2b3fb"
version = "0.1.0"
authors = ["wenigwil <github@wenigwil.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BenchmarkTools = "1.6.3"
LinearAlgebra = "1.12.0"
Logging = "1.11.0"
PGFPlotsX = "1.6.2"
Plots = "1.41.2"
